import type { TranslationKey } from "./translations.keys";

// Accounting (GL) module dictionary. Merged in translations.ts.
export const enAccounting = {
  accounting: "Accounting", chartOfAccounts: "Chart of accounts", generalLedger: "General ledger",
  accountCode: "Code", accountName: "Name", parentAccount: "Parent account",
  header: "Header", systemAccount: "System", postable: "postable", inactive: "Inactive",
  asset: "Asset", liability: "Liability", equity: "Equity", revenue: "Revenue", expense: "Expense", cogs: "COGS",
  createAccount: "New account", editAccount: "Edit account", inactiveAccounts: "Show inactive",
  activate: "Activate", expand: "Expand", collapse: "Collapse",
  doubleEntryAccounting: "Double-entry accounting", glEnabled: "Enabled", glDisabled: "Disabled",
  enableGLHint: "Enables the general ledger with automatic Dr/Cr entries. A standard chart of accounts will be created.",
  enableGLWarning: "Double-entry accounting will be activated. All new expenses, income, invoices and payroll will generate accounting entries automatically. Continue?",
  glEnabledMsg: "Accounting enabled. Transactions now generate journal entries.",
  glDisabledMsg: "Accounting disabled. Existing entries are kept.",
  entriesTab: "Entries", trialBalance: "Trial balance",
  entryNumber: "No.", entryDate: "Date", origin: "Source", state: "Status", totals: "Totals",
  debit: "Debit", credit: "Credit", balanceCol: "Balance", unbalanced: "Unbalanced", balanced: "Balanced", accountingEquation: "Accounting equation",
  voidReason: "Void reason", autoGenerated: "Auto-generated",
  noEntries: "No entries for this period.", entriesAuto: "Entries are generated automatically when you record expenses, income, invoices and payroll.",
  allMonths: "All year", allSources: "All", allStatuses: "All", allAccounts: "All accounts",
  sExpense: "Expense", sIncome: "Income", sInvoice: "Invoice", sInvoicePayment: "Payment", sPayroll: "Payroll", sInventory: "Inventory", sBank: "Bank", sAdjustment: "Adjustment", sClosing: "Closing", sOpening: "Opening",
  stPosted: "Posted", stDraft: "Draft", stVoided: "Voided",
  categoryMapping: "Category mapping", useAuto: "Automatic", autoMapAll: "Auto-assign all", mappingComplete: "Mapping complete", catsMapped: "categories mapped",
} satisfies Partial<Record<TranslationKey, string>>;
