import { Fragment, useState } from "react";
import { ChevronRight, ChevronDown } from "lucide-react";
import { useI18n } from "@shared/i18n";
import { formatCurrency } from "@shared/lib/format";
import { Pagination } from "@shared/components/Pagination";
import { SOURCE_META, STATUS_META } from "@accounting/presentation/journal-ui";
import { EntryActions } from "@accounting/presentation/EntryActions";
import type { JournalEntry } from "@accounting/domain/journal-entry.types";

// Tabla del libro mayor con filas expandibles (líneas Dr/Cr). Los asientos manuales exponen acciones si canEdit (CEO).
export function JournalEntriesTable({ entries, cost, canEdit = false, onChanged = () => {} }: { entries: readonly JournalEntry[]; cost: boolean; canEdit?: boolean; onChanged?: () => void }) {
  const { t } = useI18n();
  const [page, setPage] = useState(1);
  const [open, setOpen] = useState<string | null>(null);
  if (entries.length === 0) return (
    <div className="rounded-lg border border-border p-6 text-center text-sm text-muted-foreground">
      <p>{t("noEntries")}</p><p className="mt-1 text-xs">{t("entriesAuto")}</p></div>
  );
  const paged = entries.slice((page - 1) * 20, page * 20);
  const th = "px-2 py-1 text-left font-bold";
  return (
    <div className="space-y-2">
      <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full text-sm">
        <thead className="bg-secondary text-xs uppercase text-muted-foreground"><tr>
          <th className="w-6" /><th className={th}>{t("entryNumber")}</th><th className={th}>{t("entryDate")}</th><th className={th}>{t("description")}</th><th className={th}>{t("origin")}</th><th className={th}>{t("state")}</th>{cost && <th className={`${th} text-right`}>{t("total")}</th>}
        </tr></thead>
        <tbody>{paged.map((e) => { const src = e.sourceType ? SOURCE_META[e.sourceType] : null; const st = STATUS_META[e.status]; const isOpen = open === e.id;
          return (<Fragment key={e.id}>
            <tr className="cursor-pointer border-t border-border hover:bg-secondary/50" onClick={() => setOpen(isOpen ? null : e.id)}>
              <td className="px-2 py-1">{isOpen ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}</td>
              <td className="px-2 py-1 font-mono text-xs">{e.entryNumber}</td>
              <td className="px-2 py-1 text-muted-foreground">{e.entryDate}</td>
              <td className="px-2 py-1">{e.description}</td>
              <td className="px-2 py-1">{src && <span className={`rounded-full px-1.5 py-0.5 text-[10px] font-bold ${src.cls}`}>{t(src.key)}</span>}</td>
              <td className="px-2 py-1"><span className={`rounded-full px-1.5 py-0.5 text-[10px] font-bold ${st.cls}`}>{t(st.key)}</span></td>
              {cost && <td className="px-2 py-1 text-right font-semibold">{formatCurrency(e.totalDebit)}</td>}
            </tr>
            {isOpen && cost && <tr className="border-t border-border bg-secondary/30"><td /><td colSpan={6} className="px-2 py-2">
              <table className="w-full text-xs"><tbody>
                {e.lines.map((l) => <tr key={l.id} className={e.status === "voided" ? "text-muted-foreground line-through" : ""}>
                  <td className="py-0.5"><span className="font-mono">{l.accountCode}</span> {l.accountName}</td>
                  <td className="py-0.5 text-right">{l.debit > 0 ? formatCurrency(l.debit) : ""}</td>
                  <td className="py-0.5 text-right">{l.credit > 0 ? formatCurrency(l.credit) : ""}</td></tr>)}
                <tr className="border-t border-border font-bold"><td className="py-0.5">{t("totals")}</td>
                  <td className="py-0.5 text-right">{formatCurrency(e.totalDebit)}</td><td className="py-0.5 text-right">{formatCurrency(e.totalCredit)}</td></tr>
              </tbody></table>
              {e.voidReason && <p className="mt-1 text-xs text-destructive">{t("voidReason")}: {e.voidReason}</p>}
              {e.entryType === "auto" && <p className="mt-1 text-[10px] text-muted-foreground">{t("autoGenerated")}</p>}
              {canEdit && <EntryActions entry={e} onChanged={onChanged} />}
            </td></tr>}
          </Fragment>); })}</tbody>
      </table></div>
      <Pagination total={entries.length} page={page} pageSize={20} onPageChange={setPage} />
    </div>
  );
}
