-- inventory-polish — proveedor "ultra completo": +28 columnas en inventory_suppliers (fiscal/pago/logística/redes/rating).
-- Solo columnas aditivas. accepted_payments/secondary_categories como text[]; rating 1-5.
alter table public.inventory_suppliers
  add column if not exists company_type text,
  add column if not exists tax_id text,
  add column if not exists tax_exempt boolean default false,
  add column if not exists tax_rate numeric(5,2),
  add column if not exists description text,
  add column if not exists website text,
  add column if not exists facebook text,
  add column if not exists instagram text,
  add column if not exists linkedin text,
  add column if not exists whatsapp text,
  add column if not exists country text default 'PR',
  add column if not exists city text,
  add column if not exists state text,
  add column if not exists zip_code text,
  add column if not exists bank_name text,
  add column if not exists bank_account text,
  add column if not exists routing_number text,
  add column if not exists accepted_payments text[],
  add column if not exists credit_limit numeric(10,2),
  add column if not exists credit_balance numeric(10,2) default 0,
  add column if not exists currency text default 'USD',
  add column if not exists catalog_url text,
  add column if not exists min_order_amount numeric(10,2),
  add column if not exists delivery_method text,
  add column if not exists return_policy text,
  add column if not exists rating int check (rating between 1 and 5),
  add column if not exists primary_category text,
  add column if not exists secondary_categories text[];
