-- 20260707000060_employee_details_benefits_health.sql
-- Expediente (§3.1 cont.): beneficios/licencias + salud/seguridad. ALTER sobre employee_details (00059).

alter table public.employee_details
  add column vacation_rate numeric default 1.25,
  add column vacation_used numeric default 0,
  add column vacation_max numeric,
  add column sick_rate numeric default 1.0,
  add column sick_used numeric default 0,
  add column sick_max numeric default 60,
  add column bonus_applies boolean default true,
  add column bonus_pct numeric default 2.0,
  add column bonus_paid numeric default 0,
  add column medical_plan boolean default false,
  add column medical_provider text,
  add column medical_policy_number text,
  add column medical_coverage text check (medical_coverage in ('individual','family')),
  add column medical_employee_contribution numeric default 0,
  add column medical_employer_contribution numeric default 0,
  add column retirement_plan boolean default false,
  add column retirement_type text,
  add column retirement_employee_pct numeric default 0,
  add column retirement_employer_match_pct numeric default 0,
  add column retirement_provider text,
  add column life_insurance boolean default false,
  add column parking boolean default false,
  add column company_vehicle boolean default false,
  add column company_phone boolean default false,
  add column other_benefits text,
  add column medical_exam_status text default 'not_done' check (medical_exam_status in ('approved','pending','not_done')),
  add column medical_exam_date date,
  add column medical_exam_next date,
  add column drug_test_status text default 'not_done' check (drug_test_status in ('negative','positive','pending','not_done')),
  add column drug_test_date date,
  add column medical_conditions text,
  add column allergies text,
  add column blood_type text check (blood_type in ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  add column current_medications text,
  add column physical_limitations text,
  add column uses_uniform boolean default false,
  add column shirt_size text,
  add column pants_size text,
  add column shoe_size text,
  add column protective_equipment text[],
  add column assigned_equipment text;
